<?php

namespace App\Imports;

use Modules\Sales\Models\Customer;
use Maatwebsite\Excel\Concerns\ToCollection;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Illuminate\Support\Collection;
use Modules\Sales\Enums\CustomerType;
use Illuminate\Support\Facades\Log;

class CustomersImport implements ToCollection, WithHeadingRow
{
    public function collection(Collection $rows)
    {
        foreach ($rows as $row) {
            // Skip empty rows
            if (!isset($row['name'])) {
                continue;
            }

            // Determine if updating by Code or Email
            $customer = null;
            if (!empty($row['code'])) {
                $customer = Customer::where('code', $row['code'])->first();
            } elseif (!empty($row['email'])) {
                $customer = Customer::where('email', $row['email'])->first();
            }

            // Prepare Data
            $data = [
                'name' => $row['name'],
                'type' => $row['type'] ?? 'individual', // Default to individual
                'email' => $row['email'],
                'phone' => $row['phone'],
                'mobile' => $row['mobile'],
                'billing_address' => $row['billing_address'],
                'shipping_address' => $row['shipping_address'],
                'tax_number' => $row['tax_number'],
                'payment_terms' => $row['payment_terms_days'] ?? 0,
                'credit_limit' => $row['credit_limit'] ?? 0,
                'contact_person' => $row['contact_person'],
                'notes' => $row['notes'],
                'is_active' => strtolower($row['is_active'] ?? 'yes') === 'yes',
                'is_blocked' => strtolower($row['is_blocked'] ?? 'no') === 'yes',
                'block_reason' => $row['block_reason'],
            ];

            if ($customer) {
                // Update existing
                $customer->update($data);
            } else {
                // Create new (Code will be auto-generated by model boot method if not provided)
                if (!empty($row['code'])) {
                    $data['code'] = $row['code'];
                }
                Customer::create($data);
            }
        }
    }
}
