<?php

namespace App\Imports;

use Modules\Purchasing\Models\Supplier;
use Maatwebsite\Excel\Concerns\ToCollection;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Log;

class SuppliersImport implements ToCollection, WithHeadingRow
{
    public function collection(Collection $rows)
    {
        foreach ($rows as $row) {
            // Skip empty rows
            if (!isset($row['name'])) {
                continue;
            }

            // Determine if updating by Code or Email
            $supplier = null;
            if (!empty($row['code'])) {
                $supplier = Supplier::where('code', $row['code'])->first();
            } elseif (!empty($row['email'])) {
                $supplier = Supplier::where('email', $row['email'])->first();
            }

            // Prepare Data
            $data = [
                'name' => $row['name'],
                'email' => $row['email'],
                'phone' => $row['phone'],
                'mobile' => $row['mobile'],
                'fax' => $row['fax'],
                'address' => $row['address'],
                'tax_number' => $row['tax_number'],
                'payment_terms' => $row['payment_terms_days'] ?? 0,
                'credit_limit' => $row['credit_limit'] ?? 0,
                'contact_person' => $row['contact_person'],
                'notes' => $row['notes'],
                'is_active' => strtolower($row['is_active'] ?? 'yes') === 'yes',
            ];

            if ($supplier) {
                // Update existing
                $supplier->update($data);
            } else {
                // Create new (Code will be auto-generated by model boot method if not provided)
                if (!empty($row['code'])) {
                    $data['code'] = $row['code'];
                }
                Supplier::create($data);
            }
        }
    }
}
