@echo off
chcp 65001 >nul 2>&1
setlocal enabledelayedexpansion
title Twinx ERP - Enable HTTPS for Scanner
color 0B

echo.
echo   Twinx ERP - HTTPS Setup (Scanner Camera Fix)
echo ==========================================
echo.

REM ─── Find XAMPP ───
set "XAMPP_PATH="
if exist "C:\xampp2\xampp-control.exe" set "XAMPP_PATH=C:\xampp2"
if "%XAMPP_PATH%"=="" if exist "C:\xampp\xampp-control.exe" set "XAMPP_PATH=C:\xampp"
if "%XAMPP_PATH%"=="" if exist "D:\xampp\xampp-control.exe" set "XAMPP_PATH=D:\xampp"

if "%XAMPP_PATH%"=="" (
    echo   ERROR: XAMPP not found!
    pause
    exit /b 1
)

echo   Found XAMPP at: !XAMPP_PATH!

REM ─── Get local IP ───
set "LOCAL_IP="
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /C:"IPv4"') do (
    if "!LOCAL_IP!"=="" (
        set "LOCAL_IP=%%a"
        set "LOCAL_IP=!LOCAL_IP: =!"
    )
)
echo   Local IP: !LOCAL_IP!

REM ─── Check if OpenSSL exists ───
set "OPENSSL=!XAMPP_PATH!\apache\bin\openssl.exe"
if not exist "!OPENSSL!" (
    echo   ERROR: OpenSSL not found at: !OPENSSL!
    pause
    exit /b 1
)
echo   OpenSSL found.

REM ─── Create SSL directory ───
set "SSL_DIR=!XAMPP_PATH!\apache\conf\ssl"
if not exist "!SSL_DIR!" mkdir "!SSL_DIR!"

REM ─── Create OpenSSL config for SAN ───
echo   Generating SSL certificate...

set "SSL_CONF=!SSL_DIR!\openssl_san.cnf"

(
echo [req]
echo default_bits = 2048
echo prompt = no
echo default_md = sha256
echo distinguished_name = dn
echo req_extensions = v3_req
echo x509_extensions = v3_req
echo.
echo [dn]
echo C = EG
echo ST = Cairo
echo L = Cairo
echo O = Twinx ERP
echo CN = Twinx Local Server
echo.
echo [v3_req]
echo subjectAltName = @alt_names
echo basicConstraints = CA:TRUE
echo keyUsage = digitalSignature, keyEncipherment
echo extendedKeyUsage = serverAuth
echo.
echo [alt_names]
echo DNS.1 = localhost
echo IP.1 = 127.0.0.1
echo IP.2 = !LOCAL_IP!
) > "!SSL_CONF!"

REM ─── Generate certificate ───
"!OPENSSL!" req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout "!SSL_DIR!\twinx.key" -out "!SSL_DIR!\twinx.crt" -config "!SSL_CONF!" 2>nul

if not exist "!SSL_DIR!\twinx.crt" (
    echo   ERROR: Failed to generate SSL certificate!
    pause
    exit /b 1
)

echo   SSL certificate generated (valid for 10 years)

REM ─── Backup original SSL config ───
set "SSL_HTTPD=!XAMPP_PATH!\apache\conf\extra\httpd-ssl.conf"
if not exist "!SSL_HTTPD!.bak" (
    copy "!SSL_HTTPD!" "!SSL_HTTPD!.bak" >nul 2>&1
    echo   Original SSL config backed up.
)

REM ─── Enable SSL module in httpd.conf ───
echo   Enabling SSL module...
set "HTTPD_CONF=!XAMPP_PATH!\apache\conf\httpd.conf"

REM Check if SSL module is already enabled
findstr /C:"LoadModule ssl_module" "!HTTPD_CONF!" | findstr /V "#" >nul 2>&1
if %errorlevel% neq 0 (
    REM Enable it by removing the comment
    powershell -NoProfile -Command "(Get-Content '!HTTPD_CONF!') -replace '#LoadModule ssl_module', 'LoadModule ssl_module' | Set-Content '!HTTPD_CONF!'"
    echo   SSL module enabled.
) else (
    echo   SSL module already enabled.
)

REM Check if httpd-ssl.conf include is enabled
findstr /C:"Include conf/extra/httpd-ssl.conf" "!HTTPD_CONF!" | findstr /V "#" >nul 2>&1
if %errorlevel% neq 0 (
    powershell -NoProfile -Command "(Get-Content '!HTTPD_CONF!') -replace '#Include conf/extra/httpd-ssl.conf', 'Include conf/extra/httpd-ssl.conf' | Set-Content '!HTTPD_CONF!'"
    echo   SSL config include enabled.
) else (
    echo   SSL config include already enabled.
)

REM ─── Write new SSL VirtualHost config ───
echo   Configuring HTTPS VirtualHost...

(
echo # Twinx ERP SSL Configuration
echo # Auto-generated by ENABLE_HTTPS.bat
echo.
echo Listen 443
echo.
echo SSLCipherSuite HIGH:MEDIUM:!MD5:!RC4:!3DES
echo SSLProxyCipherSuite HIGH:MEDIUM:!MD5:!RC4:!3DES
echo SSLHonorCipherOrder on
echo SSLProtocol all -SSLv3
echo SSLProxyProtocol all -SSLv3
echo SSLPassPhraseDialog  builtin
echo SSLSessionCache "shmcb:!XAMPP_PATH!/apache/logs/ssl_scache(512000)"
echo SSLSessionCacheTimeout  300
echo.
echo ^<VirtualHost _default_:443^>
echo     DocumentRoot "!XAMPP_PATH!/htdocs"
echo     ServerName localhost:443
echo     ServerAdmin admin@localhost
echo     ErrorLog "!XAMPP_PATH!/apache/logs/error-ssl.log"
echo     TransferLog "!XAMPP_PATH!/apache/logs/access-ssl.log"
echo.
echo     SSLEngine on
echo     SSLCertificateFile "!SSL_DIR!/twinx.crt"
echo     SSLCertificateKeyFile "!SSL_DIR!/twinx.key"
echo.
echo     ^<Directory "!XAMPP_PATH!/htdocs"^>
echo         Options Indexes FollowSymLinks Includes ExecCGI
echo         AllowOverride All
echo         Require all granted
echo     ^</Directory^>
echo ^</VirtualHost^>
) > "!SSL_HTTPD!"

echo   HTTPS VirtualHost configured on port 443.

REM ─── Restart Apache ───
echo.
echo   Restarting Apache...
taskkill /F /IM httpd.exe /T >nul 2>&1
timeout /t 2 /nobreak >nul
start /B "" "!XAMPP_PATH!\apache\bin\httpd.exe" >nul 2>&1
timeout /t 3 /nobreak >nul

REM Verify
netstat -an 2>nul | findstr ":443 " | findstr "LISTENING" >nul 2>&1
if %errorlevel% equ 0 (
    echo   Apache HTTPS is running on port 443!
) else (
    echo   WARNING: Port 443 not detected yet. Apache may need manual restart.
    echo   Open XAMPP Control Panel, Stop Apache, then Start again.
)

echo.
echo ==========================================
echo   HTTPS SETUP COMPLETE
echo ==========================================
echo.
echo   Scanner URL for phones:
echo   https://!LOCAL_IP!/twinx-erp/public/scanner
echo.
echo   IMPORTANT: First time opening on each phone,
echo   Chrome will show "Your connection is not private".
echo   Click "Advanced" then "Proceed" to continue.
echo   This only happens ONCE per device.
echo.
echo ==========================================
pause
